version: '3'
services:
  code_server:
    build: .
    container_name: code-server
    volumes:
      - code-server:/config
    environment:
      - TZ=Europe/Berlin
      - SUDO_PASSWORD=password
      - PASSWORD=password
    ports:
      - 8443:8443
    restart: unless-stopped
volumes:
  code-server:
